### ISSUE TITLE
Rate parameter sets

### ISSUE THREAD

**Issue by Trevoke** [Trevoke/dfworldgen#2]
How do we rate?

+1 / -1 ? (simple)

1-5 stars? (average the results?) (do we weigh by number of stars instead of averaging?)

Something else?

**Comment by yamamushi** [comment]
Do we want a scaled model like reddit, or a simple 1-5 scorecard? 

Perhaps we have a voting model like reddit for worlds, and then a 1-5 scorecard to rate the quality of worlds individually?

**Comment by Trevoke** [comment]
I'm not sure I catch what the difference is. Are they two different ways to sort? Are we sorting two different things?

**Comment by yamamushi** [comment]
Two different things, maybe that's a waste though. I don't know which works better, maybe a single 1-10 scale instead?

**Comment by Trevoke** [comment]
I'm tempted to start with just a 1-5 star rating, averaged. And if it's not good enough, we do something else.

**Comment by yamamushi** [comment]
Agreed.
