### ISSUE TITLE
Is 'Seed' a good name?

### ISSUE THREAD

**Issue by Trevoke** [Trevoke/dfworldgen#3]
Based on Wiki, should be called ParameterSet

**Comment by yamamushi** [comment]
Seed should apply to the actual "seeds" in the worldgen files... 

Maybe, parameters?

**Comment by Trevoke** [comment]
worldgen.parameters. I like it.
Alright... We'll rename 'Seeds' WorldGens.

**Comment by yamamushi** [comment]
The wiki refers to them as "Parameter Sets" too, http://dwarffortresswiki.org/index.php/v0.31:Advanced_world_generation

**Comment by Trevoke** [comment]
Ah-ha. Okay. Now ... Do you think we need to be able to search each parameter in a set? like megabeast count, civ count, site count?

**Comment by yamamushi** [comment]
I don't see why not, being able to search across the site for something like:

All worlds with titans greater than 100

**Comment by Trevoke** [comment]
I just moved this to its own issue - it's worth its own conversation.

**Comment by Trevoke** [comment]
Alright. Parameter Sets they are.
