### ISSUE TITLE
Add user registration to site for uploading

### ISSUE THREAD

**Issue by Trevoke** [Trevoke/dfworldgen#6]
Also, of course, add an 'author' field to ParameterSet

**Comment by yamamushi** [comment]
I think we should require a registration to upload a parameter set and to vote on them/leave comments, but just downloading and browsing should be open to everyone.

**Comment by Trevoke** [comment]
Good point. So:
- downloading/browsing, open to all.
- uploading seeds, only registered users.

I'm thinking we don't need this in the first release. We can leave it open to all. If it becomes a problem before we add registration (spambots somehow take over), well, we can erase the data. As long as we tell people this is an alpha release and don't expect any data to be stored long-term, I think it should be fine.

**Comment by yamamushi** [comment]
Shouldn't be a huge problem with spambots at first, so for a beta rollout we should be fine leaving it open for everyone.

**Comment by Trevoke** [comment]
Well, I went and implemented a basic registration anyway - it was needed for the upvote/downvote thing.

I just need to restrict it so you can only edit your own seeds :p
